### ISSUE TITLE
Octoprint just stalls with bed heating

### ISSUE THREAD

**Issue by nubbyless** [EddyBeaupre/Tronxy-XY2-Pro#1]
Hi if I don't home all first before starting a print octoprint just sits heating bed indefinitely or until I hit home all and then the print will proceed as normal do you think this an issue in the start code?

**Comment by nubbyless** [comment]
update /fix i changed below lines to specify the temperature and problem was gone 
old code
M140 S{material_bed_temperature_layer_0} ; Heat bed to layer 0 setting
M190 S{material_bed_temperature_layer_0} ; Wait for bed to heat
new code
M140 S60 ; Heat bed to layer 0 setting
M190 S60 ; Wait for bed to heat

**Comment by nubbyless** [comment]
further update i had to do this for the nozzle as well like below turns out cura slicer doesn't support calculating the values in the start gcode 
old
M104 S{material_print_temperature_layer_0} T0 ; Heat nozzle to layer 0 setting
M109 S{material_print_temperature_layer_0} T0 ; Wait for nozzle to heat
new
M104 S200 T0 ; Heat nozzle to layer 0 setting
M109 S200 T0 ; Wait for nozzle to heat

**Comment by EddyBeaupre** [comment]
Work for me with cura 4.13.1/Octoprint. No issue with using "S{material_print_temperature_layer_0}". If you force the layer 0 settings, you will need to change your start g-code each time you change material.
